#! /usr/local/bin/python -O

"""
Dummy VFS for Midnight Commander. Just for a test.

Author: Oleg BroytMann <phd@phd.pp.ru>.
Copyright (C) 2004 PhiloSoft Design.
License: GPL.

"""

__version__ = "0.1.0"
__revision__ = "$Id: dummy,v 1.2 2004/06/12 22:42:29 phd Exp $"
__date__ = "$Date: 2004/06/12 22:42:29 $"[7:-2]
__author__ = "Oleg Broytmann <phd@phd.pp.ru>"
__copyright__ = "Copyright (C) 2004 PhiloSoft Design"

import sys

def log_error(msg):
   sys.stderr.write(msg + '\n')

def error(msg):
   sys.stderr.write(msg + '\n')
   sys.exit(1)


if len(sys.argv) < 2:
   error("""\
It is not a program - it is a dummy VFS for Midnight Commander.
Put it in /usr/lib/mc/extfs.""")


def mcdummy_list():
   """List the entire VFS"""
   # Ignore the VFS name (sys.argv[2])
   # Emit a dummy listing
   print "-r--r--r-- 1 user group 0 Jun 13 02:20 file0"
   print "-r--r--r-- 1 user group 1 Jun 13 02:21 file1"
   print "-r--r--r-- 1 user group 2 Jun 13 02:22 file2"


command = sys.argv[1]
g = globals()
procname = "mcdummy_" + command

if not g.has_key(procname):
   error("Unknown command %s" % command)

g[procname]()
